# Generated by Django 5.2.8 on 2025-11-19 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('registration', models.CharField(max_length=7)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
