# Generated by Django 5.2.8 on 2025-11-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
